package enums;

public enum AuditEventType {
	WALLET_CREATED,
	WALLET_ACTIVATED,
	WALLET_BLOCKED,
	WALLET_UNBLOCKED,
	TRANSFER_INITIATED,
	TRANSFER_SUCCESS,
	TRANSFER_FAILED,
	ROLLBACK,
	ROLLBACK_INITIATED,
	ROLLBACK_SUCCESS,
	ROLLBACK_FAILED,
	CREDIT,
	DEBIT,
	TRANSACTION_CREATED,
}